[package]
name = "teletype"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intel8080 = { path = "../intel8080" }
console = "0.14.1"
