[package]
name = "teletype"
version = "0.1.0"
edition = "2018"
authors = ["Nicolas BAUW <nbauw@hotmail.com>"]
description = "Teletype emulator for my 8080 emulator (88-SIO)"
keywords = ["emulation", "emulator", "teletype", "8080", "SIO"]
categories = ["emulators"]
license = "MIT"
repository = "https://github.com/nicolasbauw/teletype"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intel8080 = "0.7.0"
console = "0.14.1"
